blank_issues_enabled: false
contact_links:
  - name: ğŸ› Model Issues
    url: https://huggingface.co/openai/gpt-oss-120b/discussions
    about: For general questions about the models, please use the Community feature on Hugging Face.
  - name: ğŸ’¡ General Feedback
    url: https://openai.com/open-models
    about: Suggest new features on our feature request page.
